name: spyda_music_retailer
description: Spy-da Music Retailer App
version: 1.0.1+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  smooth_page_indicator: ^2.0.1
  webview_flutter: ^4.13.0
  mailer: ^6.6.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1  # Add this

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
    - assets/images/onboarding4.jpg
    - assets/images/splash.jpg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

# Add flutter_launcher_icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Your main app icon
  adaptive_icon_background: "#000000"  # Black background for adaptive icon
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"  # Your splash icon
  remove_alpha_ios: true
  min_sdk_android: 21